title: 技术文章
subtitle: 分享我的技术文章和学习笔记

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: articles

categories:
  - name: 最新文章
    icon: fas fa-pen
    sites:
      - name: Vue3最佳实践
        icon: fab fa-vuejs
        description: Vue3组合式API的使用技巧
        url: "#"
      - name: JavaScript进阶
        icon: fab fa-js
        description: JavaScript高级特性解析
        url: "#"
      - name: Git使用技巧
        icon: fab fa-git-alt
        description: Git常用命令和工作流
        url: "#"
      - name: Docker入门
        icon: fab fa-docker
        description: Docker基础知识和实践
        url: "#"
  - name: 学习笔记
    icon: fas fa-book
    sites:
      - name: 通路高亮标记基因
        icon: fab fa-react
        description: Kegg 通路
        url: "https://mp.weixin.qq.com/s/GZ4mILvzM6LuaaNa7feAOg?scene=1"
