title: 技术文章
subtitle: 分享我的技术文章和学习笔记

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: articles

categories:
  - name: 学习工具
    icon: fas fa-pen
    sites:
      - name: DiffDock
        icon: fab fa-vuejs
        description: 扩散模型 分子对接
        url: "https://mp.weixin.qq.com/s/WPKvpzX8fpPJyiIuZ3k_kg"
  - name: 学习笔记
    icon: fas fa-book
    sites:
      - name: 通路高亮标记基因
        icon: fab fa-react
        description: Kegg 通路
        url: "https://mp.weixin.qq.com/s/GZ4mILvzM6LuaaNa7feAOg?scene=1"
