title: 我的书签
subtitle: 从浏览器导入的书签收藏

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: bookmarks

categories:
  - name: Jav资源
    icon: fas fa-folder
    sites:
      - name: Jable
        url: https://jable.tv/
        icon: fab fa-github
        description: "在线Jav"
      - name: Stack Overflow
        url: https://stackoverflow.com/
        icon: fab fa-stack-overflow
        description: "从书签导入: Stack Overflow"
      - name: MDN Web Docs
        url: https://developer.mozilla.org/
        icon: fas fa-link
        description: "从书签导入: MDN Web Docs"
  - name: 自建网站
    icon: fas fa-folder
    sites:
      - name: Calcium
        url: https://calcium-eta.vercel.app/
        icon: fab fa-twitter
        description: "科学计算器"
      - name: Excalidraw
        url: https://excalidraw-self-tau.vercel.app/
        icon: fab fa-linkedin
        description: "画图绘图" 
