title: 友情链接
subtitle: 优秀的博主和朋友们

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: friends

categories:
  - name: 技术博主
    icon: fas fa-user-friends
    sites:
      - name: Explorer
        icon: fas fa-code
        description: 综述结构 写作
        url: "https://explorer.globe.engineer/"
  - name: 技术社区
    icon: fas fa-laptop-code
    sites:
      - name: GitHub
        icon: fab fa-github
        description: 开源代码托管平台
        url: https://github.com
