title: 欢迎使用
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: home

categories:
  - name: 常用网站
    icon: fas fa-star
    sites:
      - name: Puresys
        url: https://www.puresys.net/
        icon: fab fa-linux
        description: 纯净系统 软件下载
  - name: 论文资源
    icon: fas fa-graduation-cap
    sites:
      - name: soarXiv
        url: https://soarxiv.org/
        icon: fas fa-play-circle
        description: 畅游论文星空
      - name: SocArxiv
        url: https://osf.io/preprints/socarxiv
        icon: fas fa-question-circle
        description: 社会科学 OSF 预印
  - name: 开发工具
    icon: fas fa-tools
    sites:
      - name: VS Code
        url: https://code.visualstudio.com
        icon: fas fa-code
        description: 强大的代码编辑器
      - name: Postman
        url: https://www.postman.com
        icon: fas fa-paper-plane
        description: API调试工具
      - name: Git
        url: https://git-scm.com
        icon: fab fa-git-alt
        description: 版本控制工具
      - name: Docker
        url: https://www.docker.com
        icon: fab fa-docker
        description: 容器化平台
  - name: 网络代理
    icon: fas fa-palette
    sites:
      - name: Nekoray
        url: https://github.com/MatsuriDayo/nekoray
        icon: fab fa-figma
        description: 梯子
      - name: Dribbble
        url: https://dribbble.com
        icon: fab fa-dribbble
        description: 设计师社区
  - name: 在线工具
    icon: fas fa-wrench
    sites:
      - name: Seeing-Theory
        url: https://seeing-theory.brown.edu/
        icon: fas fa-code-branch
        description: 可视化统计
      - name: Can I Use
        url: https://caniuse.com
        icon: fas fa-browser
        description: 浏览器兼容性查询
      - name: TinyPNG
        url: https://tinypng.com
        icon: fas fa-compress
        description: 图片压缩工具
      - name: Carbon
        url: https://carbon.now.sh
        icon: fas fa-code
        description: 代码图片生成器
  - name: 分子对接
    icon: fas fa-wrench
    sites:
      - name: ReverseDock
        url: https://reversedock.biologie.uni-freiburg.de/
        icon: fas fa-code-branch
        description: 反向找靶
