title: 我的项目
subtitle: 这里展示了我的一些个人项目和开源贡献

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 游戏项目
    icon: fas fa-code
    sites:
      - name: Steam Tools
        icon: fas fa-compass
        description: Steam 解锁
        url: "https://github.com/SteamAutoCracks/ManifestHub"
      - name: Nikke
        icon: fas fa-blog
        description: 胜利女神
        url: "https://github.com/EpinelPS/EpinelPS"
  - name: 科研项目
    icon: fas fa-code
    sites:
      - name: Deep Literature
        icon: fas fa-tasks
        description: Deep Literature
        url: "https://github.com/ScienceOne-AI/DeepLiterature"
      - name: 个人博客
        icon: fas fa-blog
        description: 使用Hexo搭建的技术博客
        url: "https://github.com/EpinelPS/EpinelPS"
  - name: Docker
    icon: fas fa-code-branch
    sites:
      - name: Project A
        icon: fab fa-github
        description: 开源项目贡献
        url: "#"
      - name: Project B
        icon: fab fa-github
        description: 开源项目贡献
        url: "#" 
  - name: Vercel
    icon: fas fa-code-branch
    sites:
      - name: Project A
        icon: fab fa-github
        description: 开源项目贡献
        url: "#"
      - name: Project B
        icon: fab fa-github
        description: 开源项目贡献
        url: "#" 
